runtime: nodejs^20.0.0

env_variables:
  CYCLIC_DB: rich-teal-octopus-kitCyclicDB
  OPEN_AI_API_KEY: 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
  MONGO_URL: mongodb://yoagency:Ucp7BkirMclKdGGW@ac-qb5ayya-shard-00-00.5e5oogu.mongodb.net:27017,ac-qb5ayya-shard-00-01.5e5oogu.mongodb.net:27017,ac-qb5ayya-shard-00-02.5e5oogu.mongodb.net:27017/?ssl=true&replicaSet=atlas-ogv1oy-shard-0&authSource=admin&retryWrites=true&w=majority
  CYCLIC_APP_ID: rich-teal-octopus-kit
  JWT_SECRET: dadafafqooei019831-4911m,d
  JWT_EXPIRESIN: 2h
  CYCLIC_URL: https://rich-teal-octopus-kit.cyclic.app
  CYCLIC_BUCKET_NAME: cyclic-rich-teal-octopus-kit-eu-west-3
